baseURL = 'https://dariakanev.github.io/CHSH-ITS-EXAM-PROJECT/'
languageCode = 'en-us'
title = 'Our CHSH Project'
theme = 'lightbi-hugo'
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params] 
mainSections = ["post","posts"]
dateFormat = "02 Jan 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Daria Kaneva, Fidan Hajili, Elizaveta Britvenkova"
  #website = "https://binovarghese.com/"
  #email = "sample@gmail.com"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #linkedin = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Notes"
#     url = "/notes/"
#     weight = 2

# [[menu.main]]
#     name = "Tags"
#     url = "/tags/blog/"
#     weight = 3

# [[menu.main]]
#     name = "Collections"
#     url = "/collections/"
#     weight = 4

[[menu.main]]
    name = "About us"
    url = "/about/"
    weight = 5



